- name: Check Role - sops
  hosts: localhost
  connection: local
  
  gather_facts: true
  gather_subset:
    - '!all'
    - 'min'
  
  roles:
    - role: ./../roles/sops

  tasks:
    - name: Info
      become: false
      ansible.builtin.debug:
        msg: |
          Architecture is '{{ arch }}'
          SOPS version '{{ sops_role_version }}' installed in '{{ sops_role_folder }}'
          AGE version '{{ sops_role_age_version }}' installed in '{{ sops_role_age_folder }}'
